### ISSUE TITLE
Flatten the global translation structure

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-translations#104]
Right now some translations are "nested": global_goals, global_targets, and global_indicators. This is actually an obstacle for various technical reasons, and a hindrance to integrations and/or conversions.

For example, displaying sdg-translations as a CSV file would be possible were it not for these nested translations.

These nested translations are also cumbersome for non-technical editors to change, because they depend on indentation and syntax.

Let's consider "flattening" them. In practice, it would mean changing things like this...

```
'1':
  short: No poverty
  title: End poverty in all its forms everywhere
```

...to something like this...

```
1_short: No poverty
1_title: End poverty in all its forms everywhere
```

Since this would be a breaking change, we should consider this carefully, and we would need to ensure that dependent projects (Open SDG) are updated accordingly.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Do you see any issues with moving forward with this? It would need to have a corresponding change in Open SDG, but I think it would be a good thing overall. Having to support this nested structure is not very sustainable, in my opinion.

**Comment by LucyGwilliamAdmin** [comment]
I can't see any issues - looks easier to deal with this way.
