### ISSUE TITLE
Forking sdg-translations

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/sdg-translations#111]
Using a [Forked release](https://github.com/Norric1Admin/sdg-translations/releases/tag/0.8.1) of `sdg-translations` returns the error:

```
Refused to load the image 'https://norric1admin.github.io/favicon.ico' because it violates the following Content Security Policy directive: "img-src data:".
```
...when linking to the [translations.json](https://norric1admin.github.io/sdg-translations/translations-0.8.1.json) in `config.yml`.

Have you come across this before @brockfanning ? Forking guidance is [still in progress](https://open-sdg.github.io/sdg-translations/developers/), but it would be useful to know how to link to forked translations for future reference.

Hope this all makes sense. Many thanks,
Chris

**Comment by brockfanning** [comment]
Cleaning up the issue queue - I don't believe this is an issue anymore. Also forking is less needed now, as this repo can more easily be used in addition to others.
