### ISSUE TITLE
Cookies translations

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/sdg-translations#227]
Key|Klaro|Suggested
----|-----|-----
all_required_notice|Hi! We need to enable some services for required website functionality.|We use some essential cookies to make this service work. They always need to be on.
consentModal_description|Here you can assess and customize the services that we'd like to use on this website. You're in charge! Enable or disable services as you see fit.|Here you can change which cookies you're happy for us to use.
consentModal_title|Services we would like to use|Cookie settings
consentNotice_changeDescription|There were changes since your last visit, please renew your consent.
consentNotice_description|Hi! Could we please enable some additional services for {purposes}? You can always change or withdraw your consent later.|We use some essential cookies to make this service work. <br><br>We’d also like to use {purposes} so we can understand how you use the service and make improvements.
consentNotice_learnMore|Let me choose|View cookies
decline|I decline|Reject additional cookies
accept|**NEW**|Accept additional cookies
purposes_functional_description|These services are essential for the correct functioning of this website. You cannot disable them here as the website would not work correctly otherwise.|Essential cookies keep your information secure, and do things like remember your preferences and the choices you make whilst you use the website. They always need to be on.
purposes_functional_title|Website functionality|Essential cookies
purposes_performance_title|Performance Optimization|Performance optimization
purposes_performance_title_lower|**NEW**|performance optimization
purposes_analytics_description|These services process personal information so that we can make improvements based on how you use the site.|These services collect information about how you use the website. We use this data to help make the website better.
purposes_analytics_title|Usage analytics|Analytics cookies
purposes_analytics_title_lower|**NEW**|analytics cookies
service_required_description|This services is always required|This service is always required
google_analytics_description|Sends information about page visits to Google for analysis|Collects information about page visits using Google Analytics

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I took a look at the text after and have mapped to text in Phill's mock up. However a couple of them are my recommendations so that they fit together better.

I've also added a couple of new ones - about to add comment referring to these on open-sdg ticket

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think the reason that Klaro tends to use the term "services" is that sometimes it is technically not "cookies" that would be added. Sometimes it's "local storage", or otherwise just your data being sent to a third party. I think it could be argued that the general public would not know the difference and "cookies" gets the idea across. But anyway just wanted to bring that up.

**Comment by brockfanning** [comment]
I believe these changes were made, so I'll close this.
