### ISSUE TITLE
Czech translation on weblate

### ISSUE THREAD

**Issue by trendspotter** [open-sdg/sdg-translations#233]
Hi,  please enable Czech language for all project files on Weblate site. Thanks!

**Comment by brockfanning** [comment]
Hi @trendspotter, thank you for the interest! Can you confirm that a Czech translation is needed for an [Open SDG](https://open-sdg.org) implementation? Any details you can provide would be helpful. Thank you!

**Comment by trendspotter** [comment]
There is no direct implementation at the moment, but I have a plan to include this service in a broader municipal smart city solution. The key to success is localization. My first attempt is tke localisation of the Decidim SW.

**Comment by brockfanning** [comment]
@trendspotter Sounds great, thanks again! We've added the language.
