### ISSUE TITLE
Review Goal short titles

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/sdg-translations#43]
Update the [Goal short titles and descriptions](https://github.com/open-sdg/sdg-translations/blob/develop/translations/en/global_goals.yml) as follows...

Goal 1
Goal 2
Goal 3
Goal 4
Goal 5
Goal 11
^^ These are all in title case and need to be in sentence case. 

Goal 16 – This should read ‘Peace, justice and strong institutions’

**Comment by brockfanning** [comment]
This is fine with me. The goal 16 change is pretty minimal, but we'll probably want to make a point of updating the translations of it afterwards.

**Comment by Norric1Admin** [comment]
@brockfanning Good point - I've added https://github.com/open-sdg/sdg-translations/issues/50
