### ISSUE TITLE
Confirm translation of target 17.2 in German

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/sdg-translations#48]
@JustusCas: The import was unclear on Target 17.2, so I did a temporary Google translation of it. Can you let me know what the correct translation should be?

* [English version](https://github.com/open-sdg/sdg-translations/blob/master/translations/en/global_targets.yml#L342)
* [Temp German version](https://github.com/open-sdg/sdg-translations/blob/master/translations/de/global_targets.yml#L389)

**Comment by JustusCas** [comment]
Opened a pull request with the correct translation

**Comment by brockfanning** [comment]
Thank you @JustusCas, I just merged it.
