### ISSUE TITLE
New translation for Goal 16 short text

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/sdg-translations#50]
The Goal 16 'short'  text needs to be altered from:
'Peace and justice - strong institutions' to 'Peace, justice and strong institutions'

**Comment by brockfanning** [comment]
This may need to be postponed until https://github.com/open-sdg/open-sdg/issues/84 is worked out.

**Comment by dougmet** [comment]
Oxford comma? "Peace, justice, and strong institutions"

**Comment by brockfanning** [comment]
We recently used the official icons as a guide for the short goal titles, so I'll close this.
